apiVersion: v1
kind: Service
metadata:
  name: incident-api-service
  namespace: residential-ops
  labels:
    app: incident-api
spec:
  type: LoadBalancer
  selector:
    app: incident-api
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  sessionAffinity: None
